### ISSUE TITLE
Some suggestions for nUpdate.Administration

### ISSUE THREAD

**Issue by selway** [dbforge/nUpdate#38]
1. The 'Tabindex' of the input element in 'NewProjectDialog' is not ordered.
2. Setting the default file name of the Save Project dialog to project name that user entered  might be better.
3.  I think that when a new project is built, the user might want to open it directly.

**Comment by ProgTrade** [comment]
Sorry for my late response. I will try to include these proposals into the next big update. 
The problem with the tab indices is already known, but I never managed to fix it.
