### ISSUE TITLE
Add feature to create a package based on an existing one

### ISSUE THREAD

**Issue by NoFear23m** [dbforge/nUpdate#59]
Since it often happens that the packages are similar (ie almost the same actions must be performed) would be a way to copy a package well.

Example: A button "Add copie" in the package administration which adds a package with the same actions and files but this package will not be saved but will just open as a dialog. Now you make only minor adjustments and saves the package.

**Comment by ProgTrade** [comment]
You may implement this for the next version and provide a pull request.
