### ISSUE TITLE
Option to kill process of host application if not close on close OR wait until it closed

### ISSUE THREAD

**Issue by Pilzinsel64** [dbforge/nUpdate#77]
My programm need a bit longer to close and that occus that the updater try to overwrite the file of the running process which is closing. This cause that a error window opens that tell me that the updater wan't able to overwrite the specific file. When I click to close the updater tries again.

But this is not realy nice for the end-user. He see the error and make a bug report to me.

How would be a option for the developer who can setup the behavior for what happens if the host application doesn't close after the updater told the process to close?
E.g. setup by changing a property "BehaviorWhenHostApplicationDoesntClose" on UpdateManager of type of an Enum with this values: ShowErrorDialog, KillProcess, WaitForProcessHasClosed

**Comment by ProgTrade** [comment]
Hi,

I can try to implement a code in the update installer that will wait until the host application has closed.
Let's see, if that can help.

**Comment by ProgTrade** [comment]
You may test the newest release to see, if it works now.

**Comment by Pilzinsel64** [comment]
I got the new version and will test it next week when I am at home. I will notify you if it works now.
