### ISSUE TITLE
Conflict between mscorlib 4.0.0.0 and 2.0.5.0 when using nuget package nUpdate.ProvideTAB

### ISSUE THREAD

**Issue by Pilzinsel64** [dbforge/nUpdate#78]
Hello,

When I built my project where the nuget package nUpdate.ProvideTAB is installed (targeting.Net Framework 4.5), I always get this line in the built output:
Der Konflikt zwischen "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" und "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" kann nicht aufgelöst werden. Auswahl von "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" nach dem Zufallsprinzip.

It says, there is an conflict between mscorlib v4.0.0.0 and v2.0.5.0 and it takes v4.0.0.0 always but after ~5 seconds delay.

Can you check it out please? It's annoying.

And it's not specific for the last update, because this problem I have since I've installed nUpdate.ProvideTAB. 

If you need more informations, tell me.

Thank you very much!

Pilzinsel64

**Comment by ProgTrade** [comment]
Hi,

do you have nUpdate installed in several projects across the solution?
Do you have any other packages installed over NuGet?

I was not able to reproduce this error to this point and I doubt that it's nUpdate-specific.
You may try `update-package -reinstall` in the package manager console, but be aware of possible other problems. So make sure you're able to rollback.

Best,
Dominic
