### ISSUE TITLE
Https error (Forbidden 403) in some plesk hoting areas 

### ISSUE THREAD

**Issue by awadsalim** [dbforge/nUpdate#79]
Hello sirs and thank you for your great work, 
I'm using your application since almost a year, but had to move the update files to another hosting area, in that area I kept getting "Forbidden 403-Access denied" error despite that the directory listing is working and Json file is accessible from the browser.

That took me three days until I accidentally found someone talking about the "user-agent" header (see this link : [https://stackoverflow.com/a/2794346](url) ), so I decided to clone your code and debug it my self.

then I changed couple places: 
1- file: "nUpdate.Shared\Updating\UpdateConfiguration.cs" 
Method : 
public static IEnumerable<UpdateConfiguration> Download(Uri configFileUri, NetworkCredential credentials, WebProxy proxy, int timeout = 10000)

Changed this code: 
```
wc.Encoding = Encoding.UTF8;
if (credentials != null)
    wc.Credentials = credentials; 
if (proxy != null)
    wc.Proxy = proxy;
```

to this:
```
wc.Encoding = Encoding.UTF8;
if (credentials != null)
    wc.Credentials = credentials;
wc.Headers.Add("user-agent", "Only a test!");
if (proxy != null)
    wc.Proxy = proxy;
```

2- file "nUpdate.ProvideTAP\Updating\UpdateConfiguration.cs", 
Method: 
 public static async Task<IEnumerable<UpdateConfiguration>> DownloadAsync(Uri configFileUri, NetworkCredential credentials, WebProxy proxy, CancellationTokenSource cancellationTokenSource = null, int timeout = 10000)
change this code: 
```
// Check for SSL and ignore it
ServicePointManager.ServerCertificateValidationCallback += delegate { return true; }; 
var request = (HttpWebRequest)WebRequest.Create(configFileUri); 
request.Timeout = timeout;
```
To this:
```
// Check for SSL and ignore it
ServicePointManager.ServerCertificateValidationCallback += delegate { return true; };

var request = (HttpWebRequest)WebRequest.Create(configFileUri);
            
request.UserAgent = "Only a test!";
request.Timeout = timeout;
```
then the issue is gone from the administration application..

So I suggest that you add an option to specify the request headers and also allow the user to specify custom client for the request and setting a default "user-agent" header for the administration and all parts of the application.

The version I'm using is v3.5.0

Thank you for your effort

**Comment by ProgTrade** [comment]
Hi,

I will see when I will have time to do so.
If you want you may also add this feature and provide a pull request.

Best,
Dominic

**Comment by dbforge** [comment]
A default user-agent header is now available (thanks to @FireEmerald) with the newest `develop-v3` commit. I will have a look at when I will be able to release a new version. Until then one may build the solution as-is and use this version.

Best,
Dominic
