### ISSUE TITLE
silent mode

### ISSUE THREAD

**Issue by furesoft** [dbforge/nUpdate#81]
please add a silent mode

**Comment by ProgTrade** [comment]
What do you mean by 'silent mode'?

**Comment by furesoft** [comment]
that no ui will be displayed

**Comment by ProgTrade** [comment]
You may just implement this using the `UpdateManager` with minimal effort.
Otherwise, if you mean the search dialog: https://github.com/ProgTrade/nUpdate/blob/master/nUpdate.Shared/Updating/UpdaterUI.cs#L59

**Comment by furesoft** [comment]
i need a version without a dependency to System.windows.forms.dll
i want to use your updater in .net core on console and avalonia apps

**Comment by ProgTrade** [comment]
That was planned for v4.x as I've based the project on .NET-Standard there.
The current version only relies on .NET Framework and Windows Forms. May you be able to add a customized project yourself?

**Comment by furesoft** [comment]
i cant
