### ISSUE TITLE
automatic version from file

### ISSUE THREAD

**Issue by furesoft** [dbforge/nUpdate#84]
hi, i have an autmatic build version enabled and i want to load the version automaticly from my assembly, but for loading is the nUpdateVersion Attribute required, that needs a seperate version string, could you remove that attribute and search for normal .net assemblyversion attribute?

**Comment by dbforge** [comment]
Do you mean in the library itself? You can just overload the constructor of the `UpdateManager` class which takes an `UpdateVersion` as optional parameter. There you can specify your assembly version as version string.

Best,
Dominic
