### ISSUE TITLE
Software is already up-to-date

### ISSUE THREAD

**Issue by Kristoffeh** [dbforge/nUpdate#90]
Hi.

I started setting up stuff the other day and i must say, this project is impressive. At first i struggled a bit but now that I've gotten used to it, its quite easy to manage packages.

I've managed to upload a package, upload another and successfully upgrade to the latest one. It works! BUT if a user already uses the latest version of the software, it shows comes up with a dialog box that says:

"There are no new updates available". Is there any way to get rid of this message if there aren't any available updates?

Let's hope I'm not missing something. Thanks!

**Comment by dbforge** [comment]
Hi,

thank you. You can use the `UpdaterUi.UseHiddenSearch` property for that. Note that then the search dialog won't show up neither.

Best,
Dominic

**Comment by Kristoffeh** [comment]
Ah.

Yeah I'm gonna need the search functionality, but not if user is on the latest version. Although, i did find a way around it.

[Pastebin](https://pastebin.com/kvPzEk3h)

**Comment by dbforge** [comment]
Hm. might be the only solution to this point. It's not that decent as the search is then executed twice, but it seems to be the only workaround for that. An alternative would be to just get the source code and adapt the  `UpdaterUI` class to your needs so that it doesn't show the `NoUpdatesFoundDialog`. Then compile it and reference the DLL.

Best,
Dominic

**Comment by Kristoffeh** [comment]
Hm yes i could give that a try. I'll update this post if i get something working eventually.

**Comment by Kristoffeh** [comment]
I did eventually make this work.
I edited UpdaterUI underin the nUpdate.ProvideTAP project. Commented out the messagebox under the following if statement:

`if (!vmUpdateSearch.UpdatesFound)`
