### ISSUE TITLE
Question: Invalid signature data found

### ISSUE THREAD

**Issue by Kristoffeh** [dbforge/nUpdate#91]
I'm currently facing this issue. I know where to look anymore, could anyone perhaps push me in a direction?

https://prnt.sc/qz75kr

> Invalid signature data found.
> nUpdate will cancel the installation of the update packages and delete them unrecoverably.

I'm using WPF.

**Comment by dbforge** [comment]
Did you set the correct public key in the `UpdateManager`?

**Comment by Kristoffeh** [comment]
Ah, i went into the administration panel and just copied over the codes at the bottom. That helped, thankyou!

Quick question while I'm at it. When opening a project in the administration thingy, and selecting _load version from assembly_. It comes up with the following message.
Any thoughts on that one? This message appeared after i converted from normal ProvideTAP to the WPFUserInterface libs.

![image](https://user-images.githubusercontent.com/10790999/74075084-4faf2800-4a11-11ea-9e5f-fcb5880a45e6.png)

**Comment by dbforge** [comment]
It seems there is detailled error information that I cannot understand (due to the foreign language). Can you tell me what it says?

**Comment by Kristoffeh** [comment]
Oh! Oops! Yes it says:

> System cannot find specified file.

**Comment by dbforge** [comment]
Hi,

can you give me the stacktrace? Right click on the message and "Copy entire message".

Best,
Dominic

**Comment by Kristoffeh** [comment]
```
System.IO.FileNotFoundException: Could not load file or assembly 'nUpdate.WPFUserInterface, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. System cannot find specified file.
Filename: nUpdate.WPFUserInterface, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null
   by System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   by System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   by System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   in System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   in System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   in System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   in nUpdate.Administration.UI.Dialogs.ProjectDialog.BrowseAssemblyButtonClicked(Object sender, EventArgs e) in C:\Users\Dominic\source\repos\nUpdate\nUpdate.Administration\UI\Dialogs\ProjectDialog.cs:linje 305

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

**Comment by dbforge** [comment]
Hi,

I am sorry. You need to give me some days to review this. Have currently no time. At least this is no major bug that prevents nUpdate from working (you can still enter the version manually), but I will have a look at it!

Best,
Dominic

**Comment by Kristoffeh** [comment]
Hey Dom!

That's okay, I'm just glad you're looking into it. I'll use manual versioning for now. Thanks!
