### ISSUE TITLE
SFTP Support

### ISSUE THREAD

**Issue by Xinnony** [dbforge/nUpdate#92]
Hi,

Can you help me for add SFTP support ?
I already look in Administration.TransferInterface but idk where to start.

Thanks.

**Comment by Xinnony** [comment]
I found another updater but i leave the issue open for the others.
I thinks this updater need SFTP support, i need another person need this support : https://www.vb-paradise.de/index.php/Thread/110666-nUpdate-Die-komfortable-Updatel%C3%B6sung/?pageNo=33

**Comment by dbforge** [comment]
Hi,

I've not yet implemented this due to time issues. Maybe someone can do that.
You need to implement the `ITransferProvider` given in the `nUpdate.Administration.TransferInterface`  and add the `ServiceProviderAttribute` in the project.

Best,
Dominic
