### ISSUE TITLE
Problems reading the "updates.json" from ftp

### ISSUE THREAD

**Issue by AndreasReitberger** [dbforge/nUpdate#95]
Hi,
I'm facing a problem. Whenever I open a project, I get following error message:

![image](https://user-images.githubusercontent.com/2952443/80395027-f4bffb00-88b2-11ea-9123-cc2e58b4a304.png)

However if I open the file in the browser, it works perfectly.
https://shatter-box.com/updater/updates.json

I just entered a text to see if the file is ok. 
If this matters, I'm using a "FTP" connection. I tried to setup a SFTP, however I always got a timeout.
Same user infos are working fine using FileZilla...

Thanks for helping out!

**Comment by dbforge** [comment]
Hi,

this issue seems to be addressed [here](https://www.mycsharp.de/wbb2/thread.php?threadid=121324) as well. I've never encountered it before. The FTP connection is fine (as it points out in the message). This is a plain HTTPS issue. Do you have the possibility to try this fix mentioned in this thread?

Best,
Dominic

**Comment by AndreasReitberger** [comment]
Sadly I don't get even the source project running. I always get an error that the files are not trusted.
![image](https://user-images.githubusercontent.com/2952443/80508234-1505bd80-8978-11ea-9a60-d264a11f4067.png)

Is there a way that you make a quick fix for this issue? This is the only reason at the moment keeping me from using nUpdate for my tool.
Thanks!

**Comment by dbforge** [comment]
On this issue, see: https://www.ericnagel.com/how-to-tips/remove-the-mark-of-the-web-visual-studio-2019.html

I could try to fix it and send you the binaries to test, if it works then.

Best,
Dominic

**Comment by dbforge** [comment]
Hi @AndreasReitberger,

please try the attached binary and report back, if it works now.
[Debug.zip](https://github.com/dbforge/nUpdate/files/4567613/Debug.zip)

**Comment by AndreasReitberger** [comment]
Hi @dbforge 
thanks for providing this update. Now it works perfectly, thank you!
