### ISSUE TITLE
Sign "nUpdateInstaller" with a Certificate

### ISSUE THREAD

**Issue by AndreasReitberger** [dbforge/nUpdate#99]
Hi,
I'm using a "CodeSigningCertificate" to sign my applications. Before I switched to nUpdate I signed the installer.exe for my application with my key, so that Windows recognize my Application as safe.
However the nUpdater Installer do not have a certificate, so most windows systems will warn that the update is not safe.

Is there a way to sign the updater with my key? I could not find the updater.exe on the FTP nor in the project.

Thanks for helping!

**Comment by dbforge** [comment]
Hi,

you are absolutely right about this. Actually I planned to buy a code signing certificate a long time ago. However, it has barely been worth it for me.
You may find the nUpdate.UpdateInstaller.exe in the Resources of the nUpdate project (library). I know this is not an ideal way to do this and in the future I would like to provide the installer inside of the packages as well. But, time is an issue, sadly.
You need to edit the project for that purpose. Get the installer executable (or compile it by yourself in Visual Studio), sign it with your key and then put it in the resources.

Best,
Dominic

**Comment by AndreasReitberger** [comment]
Hi @dbforge 
thanks for your quick reply. I'll try the steps you mentioned. 
If you want, I can provide you a signed exe file for the updater.
I guess it's better if it's signed with any certificate, as with none.

Just let me know.

Best,
Andreas

**Comment by dbforge** [comment]
Hi,

thank you. Sure, why not. This would be way better than the yellow warning dialog that is currently appearing.
As it may still take some time until I can roll out the bigger update and maybe buy a certificate myself, this would be great.

Best,
Dominic
